// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://humfvpepydkbgtshgovg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1bWZ2cGVweWRrYmd0c2hnb3ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MTk1NjEsImV4cCI6MjA2Njk5NTU2MX0.YDTqDQtf43DlXOufyTX3qy0sRV0dC7dhmuZvK6yocXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});